version: '3'

services:
  # Node.js Application
  app:
    build:
      context: .
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    environment:
      DATABASE_URL: "mongodb://mongo/argentBankDB"  # Use the service name 'mongo' as the hostname

  # MongoDB
  mongo:
    image: mongo
    user: '502:502'
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db:rw

volumes:
  mongo:
    external: true